SonarSource/sonar-scanner-cli

src/main/assembly/bin/sonar-scanner

Didn't work for me until I added this flag.
http://stackoverflow.com/a/7666/2662707

add -P to full path resolution

---

src/test/java/org/sonarsource/scanner/cli/CliTest.java

Add more unit tests regarding the --embedded switch

---

pom.xml

Update sonar-scanner-api to version 2.12

SQSCANNER-55 update sonar-scanner-api

---

src/main/java/org/sonarsource/scanner/cli/Logs.java
src/test/java/org/sonarsource/scanner/cli/LogsTest.java

Redirect warnings to stdout instead of stderr.

SQSCANNER-54 don't print warnings to stderr

---

it/pom.xml
it/src/test/java/com/sonarsource/scanner/it/DistributionTest.java
it/src/test/java/com/sonarsource/scanner/it/MultimoduleTest.java
it/src/test/java/com/sonarsource/scanner/it/ScannerTest.java
it/src/test/java/com/sonarsource/scanner/it/ScannerTestCase.java

Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-cli/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:

Upgrade sonar-ws in ITs to v7.9.1

---

it/pom.xml
it/src/test/java/com/sonarsource/scanner/it/DistributionTest.java
it/src/test/java/com/sonarsource/scanner/it/MultimoduleTest.java
it/src/test/java/com/sonarsource/scanner/it/ScannerTest.java
it/src/test/java/com/sonarsource/scanner/it/ScannerTestCase.java
it/src/test/java/com/sonarsource/scanner/it/SonarScannerTestSuite.java
pom.xml
src/main/java/org/sonarsource/scanner/cli/Cli.java
src/main/java/org/sonarsource/scanner/cli/Conf.java
src/main/java/org/sonarsource/scanner/cli/Exit.java
src/main/java/org/sonarsource/scanner/cli/Logs.java
src/main/java/org/sonarsource/scanner/cli/Main.java
src/main/java/org/sonarsource/scanner/cli/PropertyResolver.java
src/main/java/org/sonarsource/scanner/cli/ScannerFactory.java
src/main/java/org/sonarsource/scanner/cli/ScannerVersion.java
src/main/java/org/sonarsource/scanner/cli/Stats.java
src/main/java/org/sonarsource/scanner/cli/SystemInfo.java
src/main/java/org/sonarsource/scanner/cli/package-info.java
src/test/java/org/sonar/api/utils/MessageException.java
src/test/java/org/sonarsource/scanner/cli/CliTest.java
src/test/java/org/sonarsource/scanner/cli/ConfTest.java
src/test/java/org/sonarsource/scanner/cli/LogsTest.java
src/test/java/org/sonarsource/scanner/cli/MainTest.java
src/test/java/org/sonarsource/scanner/cli/PropertyResolverTest.java
src/test/java/org/sonarsource/scanner/cli/ScannerFactoryTest.java
src/test/java/org/sonarsource/scanner/cli/StatsTest.java
src/test/java/org/sonarsource/scanner/cli/SystemInfoTest.java

Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-cli/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:

SQSCANNER-79 Changed name of scanner to SonarScanner CLI

---

.github/workflows/release.yml

Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-cli/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:

Add release with GH Actions.

---

.cirrus.yml
it/docker/Dockerfile
it/packer/sonar-scanner-cli-qa.json

Move ci builds to sonarqube team gcp project.

---

it/pom.xml
it/src/test/java/com/sonarsource/scanner/it/SonarScannerTestSuite.java
misc/symlink-tester.sh
src/main/assembly/bin/sonar-scanner
src/main/assembly/bin/sonar-scanner-debug

In response to https://community.sonarsource.com/t/sonarqube-scanner-failing-with-syntax-error-at-line-16-target-unexpected/6424/5

SQSCANNER-78 - backtick syntax

---

it/src/test/java/com/sonarsource/scanner/it/SonarScannerTestSuite.java

Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-cli/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:

SQSCANNER-83 - Test cleanup

---

src/main/assembly/bin/sonar-scanner
src/main/assembly/bin/sonar-scanner-debug
src/main/assembly/bin/sonar-scanner-debug.bat
src/main/assembly/bin/sonar-scanner.bat

SQSCANNER-70 - Updated script comments

---

src/main/java/org/sonarsource/scanner/cli/Cli.java
src/test/java/org/sonarsource/scanner/cli/CliTest.java

SQSCANNER-67 - Warn on duplicate property definitions

---

.github/workflows/release.yml

SQSCANNER-68 - Automatically trigger docker release on new CLI release

---

it/packer/sonar-scanner-cli-qa.json

Update target region of packer image build.

---

it/pom.xml
pom.xml

Bump junit to 4.13.1

---

it/pom.xml
it/src/test/java/com/sonarsource/scanner/it/DistributionTest.java
it/src/test/java/com/sonarsource/scanner/it/MultimoduleTest.java
it/src/test/java/com/sonarsource/scanner/it/ScannerTest.java
it/src/test/java/com/sonarsource/scanner/it/ScannerTestCase.java

Upgrade Orchestrator to 3.33.0.2677

---

.github/workflows/release.yml

BUILD Switch to maintained release action

---

it/packer/README.md

Fix the documentation of IT on Windows

---

pom.xml

BUILD-1443: generate SBOM
Activate cyclonedx-maven-plugin
Upgrade to parent 61.0.139

feat(BUILD-1443): sbom plugin

---

it/src/test/java/com/sonarsource/scanner/it/ScannerTestCase.java
pom.xml

Releasibility check is failing, this was suggested by burgr. Also by the way the ITs are failing on master. So fixing it.

NO-JIRA fixing version of base pom

---

.cirrus.yml

BUILD-2026 Remove the suffix of CirrusCI role and K8s Cluster name

---

.cirrus.yml
.github/workflows/release.yml
it/pom.xml
it/src/test/java/com/sonarsource/scanner/it/SonarScannerTestSuite.java

This PR ensures that secrets are being fetched from HashiCorp Vault.

BUILD-2144 Fetch secrets from Vault

---

.cirrus.yml
it/pom.xml
pom.xml

Build with Java 17 and Package Java 17

---

pom.xml
src/main/assembly/dist-linux.xml

Fix packaging java 17

---

.cirrus.yml
.github/workflows/release.yml
it/pom.xml
it/projects/simple-js/file.js
it/src/test/java/com/sonarsource/scanner/it/ScannerTest.java
it/src/test/java/com/sonarsource/scanner/it/ScannerTestCase.java
it/src/test/java/com/sonarsource/scanner/it/SonarScannerTestSuite.java

@tom-vanbraband-sonarsource Test with the new orchestrator. The orchestrator hasn't been released so this can't be merged

Add IT with new orchestrator

---

pom.xml
src/main/java/org/sonarsource/scanner/cli/Exit.java
src/main/java/org/sonarsource/scanner/cli/Main.java
src/main/java/org/sonarsource/scanner/cli/Stats.java
src/test/java/org/sonarsource/scanner/cli/MainTest.java
src/test/java/org/sonarsource/scanner/cli/StatsTest.java

Another round of log improvements

Log improvements

---

README.md

SC-17118 Rebranding effort

---

.github/workflows/releasability.yml

[SCANCLI-164](https://sonarsource.atlassian.net/browse/SCANCLI-164)
[SCANCLI-164]: https://sonarsource.atlassian.net/browse/SCANCLI-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-164 Add releasability workflow

---

it/pom.xml
it/src/test/java/com/sonarsource/scanner/it/DistributionTest.java
it/src/test/java/com/sonarsource/scanner/it/MultimoduleTest.java
it/src/test/java/com/sonarsource/scanner/it/ScannerTest.java
it/src/test/java/com/sonarsource/scanner/it/ScannerTestCase.java
it/src/test/java/com/sonarsource/scanner/it/SonarScannerTestSuite.java
pom.xml
src/main/java/org/sonarsource/scanner/cli/Cli.java
src/main/java/org/sonarsource/scanner/cli/Conf.java
src/main/java/org/sonarsource/scanner/cli/Exit.java
src/main/java/org/sonarsource/scanner/cli/Main.java
src/main/java/org/sonarsource/scanner/cli/PropertyResolver.java
src/main/java/org/sonarsource/scanner/cli/ScannerEngineBootstrapperFactory.java
src/main/java/org/sonarsource/scanner/cli/ScannerVersion.java
src/main/java/org/sonarsource/scanner/cli/Stats.java
src/main/java/org/sonarsource/scanner/cli/SystemInfo.java
src/main/java/org/sonarsource/scanner/cli/package-info.java
src/test/java/org/sonar/api/utils/MessageException.java
src/test/java/org/sonarsource/scanner/cli/CliTest.java
src/test/java/org/sonarsource/scanner/cli/ConfTest.java
src/test/java/org/sonarsource/scanner/cli/MainTest.java
src/test/java/org/sonarsource/scanner/cli/PropertyResolverTest.java
src/test/java/org/sonarsource/scanner/cli/ScannerEngineBootstrapperFactoryTest.java
src/test/java/org/sonarsource/scanner/cli/StatsTest.java
src/test/java/org/sonarsource/scanner/cli/SystemInfoTest.java
src/test/java/testutils/ConcurrentListAppender.java
src/test/java/testutils/LogTester.java

[SCANCLI-166](https://sonarsource.atlassian.net/browse/SCANCLI-166)
[SCANCLI-166]: https://sonarsource.atlassian.net/browse/SCANCLI-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-166 Update license headers for 2025

---

.github/workflows/releasability.yml

[SCANCLI-167](https://sonarsource.atlassian.net/browse/SCANCLI-167)
[SCANCLI-167]: https://sonarsource.atlassian.net/browse/SCANCLI-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-167 Bump releasability action to 2.1.2

---

.github/workflows/release.yml

[SCANCLI-169](https://sonarsource.atlassian.net/browse/SCANCLI-169)
[SCANCLI-169]: https://sonarsource.atlassian.net/browse/SCANCLI-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-169 Change slack channel for release notification

---

pom.xml

[SCANCLI-170](https://sonarsource.atlassian.net/browse/SCANCLI-170)
[SCANCLI-170]: https://sonarsource.atlassian.net/browse/SCANCLI-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-170 Update logback to 1.5.13

---

pom.xml

[REL-3510](https://sonarsource.atlassian.net/browse/REL-3510)

REL-3510 Prepare next dev iteration

---

pom.xml

[REL-3541](https://sonarsource.atlassian.net/browse/REL-3541)

REL-3541 Prepare next dev iteration

---

.github/workflows/PullRequestClosed.yml

[SCANCLI-177](https://sonarsource.atlassian.net/browse/SCANCLI-177)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SCANCLI-177]: https://sonarsource.atlassian.net/browse/SCANCLI-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-177 Autoclose issues created by Jira integration

---

pom.xml

[REL-3635](https://sonarsource.atlassian.net/browse/REL-3635)
[REL-3635]: https://sonarsource.atlassian.net/browse/REL-3635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

REL-3635 Prepare next dev iteration

---

it/pom.xml

[SCANCLI-179](https://sonarsource.atlassian.net/browse/SCANCLI-179)
Thank You!
[SCANCLI-179]: …

SCANCLI-179 Upgrade to latest Orchestrator

---

it/pom.xml

[SCANCLI-181](https://sonarsource.atlassian.net/browse/SCANCLI-181)
Thank You!
[SCANCLI-181]: …

SCANCLI-181 Bump sonar-ws version

---

.github/workflows/releasability.yml

[SCANCLI-186](https://sonarsource.atlassian.net/browse/SCANCLI-186)
[SCANCLI-186]: https://sonarsource.atlassian.net/browse/SCANCLI-186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-186 Fix the releasability check

---

it/pom.xml
pom.xml

[SCANCLI-188](https://sonarsource.atlassian.net/browse/SCANCLI-188)
[SCANCLI-188]: https://sonarsource.atlassian.net/browse/SCANCLI-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-188 Update dependencies

---

pom.xml

[SCANCLI-187](https://sonarsource.atlassian.net/browse/SCANCLI-187)
[SCANCLI-187]: https://sonarsource.atlassian.net/browse/SCANCLI-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-187 Update to the latest Scanner Java library

---

src/main/java/org/sonarsource/scanner/cli/SystemInfo.java
src/test/java/org/sonarsource/scanner/cli/SystemInfoTest.java

[SCANCLI-173](https://sonarsource.atlassian.net/browse/SCANCLI-173)
[SCANCLI-173]: https://sonarsource.atlassian.net/browse/SCANCLI-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-173 Switch the log of SONAR_SCANNER_OPTS to debug

---

.claude/update-jres.md
CLAUDE.md
pom.xml
src/main/assembly/dist-linux-aarch64.xml
src/main/assembly/dist-linux-x64.xml
src/main/assembly/dist-macosx-aarch64.xml
src/main/assembly/dist-macosx-x64.xml

[SCANCLI-189](https://sonarsource.atlassian.net/browse/SCANCLI-189)
[SCANCLI-189]: https://sonarsource.atlassian.net/browse/SCANCLI-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-189 Update JREs to 17.0.15+6

---

.github/workflows/releasability.yml
.github/workflows/release.yml

[SCANCLI-193](https://sonarsource.atlassian.net/browse/SCANCLI-193)
Thank You!
[SCANCLI-193]: …

SCANCLI-193 Update the release and releasability actions

---

pom.xml

[SCANCLI-194](https://sonarsource.atlassian.net/browse/SCANCLI-194)
[SCANCLI-194]: https://sonarsource.atlassian.net/browse/SCANCLI-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANCLI-194 Upgrade sonar-scanner-java-library to 3.5.0.539
